### ISSUE TITLE
trying to understand Prop definition

### ISSUE THREAD

**Issue by htzh** [leanprover/tutorial#102]
I had first defined certain properties like:
```
definition mul_closed_on H := ∀ x y, (x ∈ H ∧ y ∈ H) → x * y ∈ H
```
Now I am trying to package it into a class for inference
```
structure is_subgroup [class] (H : set A) : Type :=
  (has_one : H 1)
  (mul_closed : mul_closed_on H)
  (has_inv : subgroup.has_inv H)
```
When I tried to create a lemma as a bridge to be compatible with what I had before:
```
lemma subg_mul_closed : mul_closed_on H := !is_subgroup.mul_closed
```
Lean complained about:
```
type mismatch at definition 'subg_mul_closed', has type
  ∀ (A : Type) (s : group A) (H : set A) (is_subg : is_subgroup H),
    ?M_2 ∈ ?M_3 ∧ ?M_4 ∈ ?M_3 → ?M_2 * ?M_4 ∈ ?M_3
but is expected to have type
  ∀ {A : Type} [s : group A] {H : set A} [is_subg : is_subgroup H],
    mul_closed_on H
```
Putting on ```local attribute mul_closed_on [reducible]``` didn't help.

**Comment by htzh** [comment]
Okay I see a problem I had, by using ```!``` I had forced the instantiation of variables, by removing ```!``` I now have:
```
type mismatch at definition 'ssubg_mul_closed', has type
  ∀ (A : Type) (s : group A) (H : set A) (is_subg : is_subgroup H) (s_1 : group ?M_1)
  (H_1 : set ?M_1) [c : is_subgroup H_1],
    mul_closed_on H_1
but is expected to have type
  ∀ {A : Type} [s : group A] {H : set A} [is_subg : is_subgroup H],
    mul_closed_on H
```

**Comment by htzh** [comment]
Okay explicit instantiation seems to work:
```
lemma subg_mul_closed : mul_closed_on H := @is_subgroup.mul_closed A s H is_subg
```

**Comment by fpvandoorn** [comment]
Some remarks:

* Taking the following (equivalent) definition is probably easier to work with
```lean
definition mul_closed_on H := ∀ x y, x ∈ H → y ∈ H → x * y ∈ H
```
* If you just want to define a shorter name for something, the following works if you don't have included variables (you can `omit` them)
```lean
lemma subg_mul_closed := @is_subgroup.mul_closed
```
* You can the following command to see which arguments are implicit and which are explicit.
```lean
check @is_subgroup.mul_closed
```

**Comment by htzh** [comment]
I want to refer to the same definition in multiple places, which is why I gave it a name. I think the problem is that I used it in different ways. In the section before the structure is defined I had H explicitly stated to avoid confusion. Afterwards in new sections I want to always refer to an instantiated instance of H. The full code is now up at https://github.com/htzh/leanproved/tree/master/group_theory . I welcome any thought you may have on it. I am new to this.
I am also wondering if your category theory library can be used to prove group hom theorems. Any thought on how/if that may work?
Oh I did notice that it is a bit more convenient to use the curried style of A -> B -> C than (A, B) -> C. I even wrote a little lemma (surprisingly it doesn't seem to exist in the library already). But in the end it doesn't bother me enough to either use the converter or rewrite the def.
```
theorem and_imp_curry (a b c : Prop) : (a ∧ b → c) = (a → b → c) :=
        propext (iff.intro (λ Pl a b, Pl (and.intro a b))
                           (λ Pr Pand, Pr (and.left Pand) (and.right Pand)))
```

**Comment by avigad** [comment]
In dependent type theory, the common convention is to use the curried form almost all the time. It is generally easier to write ```foo H1H2``` than ```foo (and.intro H1 H2)```, it works better with partial application, and this way you don't have to think about which form was chosen.

**Comment by htzh** [comment]
Okay I will refactor the code. It should only be changes in a few places.
