### ISSUE TITLE
Why is this accepted as correct or how does rewrite know about assoc laws?

### ISSUE THREAD

**Issue by htzh** [leanprover/tutorial#105]
This piece of rewrite seems like magic. I am happy with the result but I am hoping it is not too good to be true https://github.com/htzh/leanproved/blob/master/group_theory/action.lean#L7-L18 :
```
variable {A : Type}
structure perm (A : Type) : Type :=
(f : A → A) (is_perm : @bijective A A f)
attribute perm.f [coercion]

definition perm.compose (g f : perm A) : perm A := 
  perm.mk (g∘f) (bijective_compose (perm.is_perm g) (perm.is_perm f))
local infix `^` := perm.compose
theorem perm.assoc (h g f : perm A) : h ^ g ^ f = h ^ (g ^ f) := 
        begin
          rewrite ↑perm.compose
        end
```
I checked that Linja compiled too just in case Emacs wasn't telling me the truth. It was a surprise because I expected to do more. Actually I wasn't even quite sure how to go about it if I had to do it manually (cases?). How does rewrite know what to use to prove it? On a related note can one see the proof terms that the kernel sees? Are they at all human readable? If not, is there a desugared intermediate format that I can study to understand some of the logic under the hood?

**Comment by leodemoura** [comment]
The proof holds by reflexivity. We can replace `begin rewrite ... end` with `rfl`.
That is, if we normalize the left and right hand sides we get the same term. For example, the normal forms for 
```lean
variable {A : Type}
variables (h g f : perm A)
eval (h ∘ g) ∘ f
eval h ∘ (g ∘ f)
``` 
are the same 
```lean
λ (x : A), h (g (f x))
```
I didn't check your definition of `bijection_compose`, but it should also hold.

> On a related note can one see the proof terms that the kernel sees?

```lean
reveal perm.compose   -- the reveal command is only needed for theorems. 
print definition perm.compose
``` 

> Are they at all human readable?

It depends. Sometimes, they are readable, but some information is lost. Example: `calc` proofs are printed as long chains of transitivity. Proofs based on tactics may be very cryptic (in particular if we use the `cases` tactic).
We can increase the amount of detail by using the options
```lean
set_option pp.implicit true
set_option pp.notation false
set_option pp.coercions true
set_option pp.universes true
```

**Comment by avigad** [comment]
I believe the proof. The two functions are definitionally equal, and then the propositional parts are equal "for free" by proof irrelevance.

You are right, though, that in general we are not so lucky, and proving the equality of two structures is a pain in the neck. We still need to write something about this in the tutorial. But in the meanwhile, there is a discussion of it in this issue:

  https://github.com/leanprover/lean/issues/550

**Comment by leodemoura** [comment]
> If not, is there a desugared intermediate format that I can study to understand some of the logic under the hood?

In the future, it would be nice to have a better pretty printer for automatically generated proofs and proofs generated using tactics. Some ideas:
- Break/present the proof in steps using `have` & `show` 
- Display transitivity chains using `calc`

**Comment by leodemoura** [comment]
Other ideas: 
- present a sequence of nested `cases_on` eliminators using `match ... with ... end`.

**Comment by htzh** [comment]
@avigad @leodemoura Thanks for patiently explaining all the finer details.
```
reveal perm.assoc
print definition perm.assoc
print result:
λ (A : Type) (h g f : perm A),
  eq.refl
    (perm.mk ((perm.f h ∘ perm.f g) ∘ perm.f f)
       (bijective_compose (bijective_compose (perm.is_perm h) (perm.is_perm g))
          (perm.is_perm f)))

reveal bijective_compose
print definition bijective_compose
print result:
λ (A : Type) (B : Type) (C : Type) (g : B → C) (f : A → B)
(Hg : bijective g) (Hf : bijective f),
  eq.subst (eq.symm bijective_eq_bij_on_univ)
    (bij_on_compose (eq.subst bijective_eq_bij_on_univ Hg)
       (eq.subst bijective_eq_bij_on_univ Hf))
```
Presumably Lean didn't go inside bijective_compose (and it should be opaque any way). So I assume this is what @avigad means:
> the propositional parts are equal "for free" by proof irrelevance.

**Comment by htzh** [comment]
However when I continued on with:
```
definition perm.one : perm A := perm.mk id id_is_bij
lemma perm.one_mul (f : perm A) : perm.one ^ f = f :=
  begin
  esimp [perm.compose, perm.one],
  rewrite *(left_id f)
  end
-- to construct an inv we need to go finite
```
I got this:
```
invalid 'rewrite' tactic, step produced type incorrect term, details:type mismatch at application
  perm.mk x (bijective_compose id_is_bij (perm.is_perm f))
term
  bijective_compose id_is_bij (perm.is_perm f)
has type
  bijective (id ∘ perm.f f)
but is expected to have type
  bijective x
rewrite step failed using pattern
  id ∘ perm.f f_1
proof state:
A : Type,
f : perm A
⊢ perm.mk (id ∘ perm.f f) (bijective_compose id_is_bij (perm.is_perm f)) = f
```
Does this look like a bug?

**Comment by avigad** [comment]
This is the more difficult case of showing that two structures are equal, as discussed in #550. The problem is that the type of the later elements of the structure depend on the first component, and when you rewrite a part of an expression the result may no longer type check. The solution is roughly to suitably generalize that claim that you are trying to prove so that types don't break, or use auxiliary theorems that do that for you.

This is a common headache with dependent rewriting, and, as I said, we really need to write a section in the tutorial explaining it. In the meanwhile, if you post your code or send it to me offline, I'll work it out for you later today.

**Comment by htzh** [comment]
Thanks for referencing https://github.com/leanprover/lean/issues/550 . I think I can figure it out following the explanation there. The code is online but I may be revising the structure shortly. I am stilling trying to figure out the right definitions to work with.

**Comment by htzh** [comment]
I tried many ways but mostly had trouble with bindings. Finally I got down to basics and this worked:
```
lemma perm.one_mul (f : perm A) : perm.one ^ f = f :=
      perm.cases_on f (λ f Hf, rfl)
```
I am still trying to get the difference between this and the assoc case. They seem rather similar to me.
