### ISSUE TITLE
In-browser version of Lean fails to show error on bad tactic proof

### ISSUE THREAD

**Issue by rlewis1988** [leanprover/tutorial#113]
A minor bug that I came across while looking something up in the tutorial.

The following proof is clearly wrong:
```lean
import data.nat

constants a m n : nat
axiom a1 : n = a

theorem t1 : m = n :=
  by rewrite a1; apply rfl
```

In emacs, Lean identifies the error. The in-browser version just gives the following output without highlighting any errors:

    -- Processing...
    -- Saved at cookie.

The problem seems to be with the compound tactic.

**Comment by soonhokong** [comment]
It actually outputs the following error message to Javascript Console:

```
Uncaught abort() at Error
    at jsStackTrace (https://leanprover.github.io/lean.js/lean.js:1:4307289)
    at stackTrace (https://leanprover.github.io/lean.js/lean.js:1:4307472)
    at abort (https://leanprover.github.io/lean.js/lean.js:107:30300)
    at Array.aie (https://leanprover.github.io/lean.js/lean.js:97:67329)
    at gjb (https://leanprover.github.io/lean.js/lean.js:61:225396)
    at kXb (https://leanprover.github.io/lean.js/lean.js:93:133755)
    at Array.lXb (https://leanprover.github.io/lean.js/lean.js:93:134198)
    at Object.iNd [as dynCall_viii] (https://leanprover.github.io/lean.js/lean.js:97:3006)
    at invoke_viii (https://leanprover.github.io/lean.js/lean.js:1:5346348)
    at ZDc (https://leanprover.github.io/lean.js/lean.js:85:192395)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.invoke_ii @ lean.js:1cf @ lean.js:9cNd @ lean.js:97lean_process_file @ VM257:6myModule.process_file @ main_live.js:1(anonymous function) @ main_live.js:1
```

**Comment by leodemoura** [comment]
The `lean.js` has not been updated in a while. I will update it asap.

**Comment by leodemoura** [comment]
I updated `lean.js`, and it is still failing. 
I tried the native binary, and everything works with different settings.
I also compiled everything locally using `--to_axiom`, and did not find any problems.
I also tried to execute the native binary using valgrind, and got 0 errors.
I don't know what to do. This is a serious issue. It seems to affect many tactics.
Here is a smaller problematic example:
```lean
example (a n : nat) (H : n = a) : n = n :=
begin
  rewrite H
end
```

@soonhokong any ideas? I couldn't make sense of the trace you posted.

**Comment by soonhokong** [comment]
Dear Leo,

I will take a look at it after dinner.

Best,
Soonho

On Tuesday, June 16, 2015, Leonardo de Moura <notifications@github.com>
wrote:

> I updated lean.js, and it is still failing.
> I tried the native binary, and everything works with different settings.
> I also compiled everything locally using --to_axiom, and did not find any
> problems.
> I also tried to execute the native binary using valgrind, and got 0 errors.
> I don't know what to do. This is a serious issue. It seems to affect many
> tactics.
> Here is a smaller problematic example:
>
> example (a n : nat) (H : n = a) : n = n :=begin
>   rewrite Hend
>
> @soonhokong <https://github.com/soonhokong> any ideas? I couldn't make
> sense of the trace you posted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leanprover/tutorial/issues/113#issuecomment-112593877>
> .
>


-- 

Best,
Soonho

**Comment by leodemoura** [comment]
Thanks!

**Comment by leodemoura** [comment]
@soonhokong Any news?
I'm worried about this issue because of the tutorial at CADE.

**Comment by soonhokong** [comment]
I was working on it last night. I had a problem compiling gmp with the latest version of emscripten SDK (known problem for 64-bit machines, but it worked before on a 32-bit machine). I think I figure out how to fix it. I'll keep you posted.

**Comment by leodemoura** [comment]
This is great news! What is the problem?

**Comment by soonhokong** [comment]
GMP checks whether a compiler supports `long long` or not by compiling a test code. I think there is a problem in the test code that they're using and it failed because of the code.

**Comment by leodemoura** [comment]
I see, you fixed the GMP problem...
I thought you had found the problem with the web version.

**Comment by soonhokong** [comment]
Anyway, I'll first compile Lean.js using a 32-bit VM machine (after fixing the above issue), then fix the original issue (which generated the JS stack trace that I mentioned above).

**Comment by soonhokong** [comment]
Sorry.. not yet :-(

**Comment by soonhokong** [comment]
@rlewis1988, I've made some updates. Could you check the two examples again on your machine?

**Comment by rlewis1988** [comment]
This seems to have fixed it! Although, the error message is a little funky:
![screen shot 2015-06-18 at 10 13 20 am](https://cloud.githubusercontent.com/assets/4967469/8221502/cff03534-15a2-11e5-88c9-0c2fb17c5a8a.png)

**Comment by soonhokong** [comment]
@rlewis1988, I see. I do have the same message.
