### ISSUE TITLE
More divergent behavior between browser and emacs

### ISSUE THREAD

**Issue by rlewis1988** [leanprover/tutorial#120]
I was trying a few toy examples in-browser while putting together slides, and found the following:
```lean
inductive foo : Type :=
 | c1 : foo → foo

check foo.c1
````
This code behaves properly in emacs. The tutorial version of Lean gives the error "unreachable code was reached." That sounds bad!

**Comment by rlewis1988** [comment]
Addendum: changing `check foo.c1` to `check nat` produces the same result.

**Comment by soonhokong** [comment]
Thanks for the report. It looks really bad. I'll take care of it soon.

**Comment by leodemoura** [comment]
It seems any `check` command produces the error.

**Comment by leodemoura** [comment]
@soonhokong Here is the followup of our email exchange this morning. 
I'm writing it here just to have record the "fix".

1- The problem has been fixed. I retracted a recent change to `format.cpp`.
https://github.com/leanprover/lean/commit/694eef7f6a2511d154c3d2172110b965c5a3d5aa
It is unclear why it affects `lean.js`, but it doesn't affect the native binary. 
Valgrind does not report any memory corruption when compiling Lean using clang++ or g++.

2- I added a unit test for the emscripten interface as you suggested.
https://github.com/leanprover/lean/commit/a24b06254b1d2a805e4ae879fc83250e973b896a
https://github.com/leanprover/lean/commit/a6fe4cbce6d5746d23b260e6c6e0f657e854e3b6
I also tried these tests using Valgrind and no memory corruption was detected.

**Comment by soonhokong** [comment]
Thank you, Leo.

I also tested the C++ binary with valgrind but couldn't find anything special. I'll add a script to test `lean.js` over testcode in the tutorial. I think we can do it using nodejs.

**Comment by leodemoura** [comment]
> I'll add a script to test lean.js over testcode in the tutorial. I think we can do it using nodejs.

Thanks!

**Comment by soonhokong** [comment]
I think we resolved this issue thanks to @leodemoura's commits. I also added the test on Travis.
