### ISSUE TITLE
5.7 Coercions

### ISSUE THREAD

**Issue by awf** [leanprover/tutorial#154]
says "a special datatype known as num", and I believe there's an implication that this will be printed as `num`:
```
check 123            -- 123 : num
```
but in fact I see (in today's https://leanprover.github.io/tutorial)
```
-- Processing...
-- Saved at cookie.
line 7, column 0: information:check result:
123 : ?M_1 a b m n
line 8, column 0: information:check result:
123 : ℕ
```

**Comment by avigad** [comment]
@awf Thanks! You are right, this is no longer correct. Numerals are now interpreted directly in any type that has a zero, one, and addition. I have repaired the example and issued a pull request.

There are likely other parts of the tutorial that are not fully up to date. We'll eventually do a full overhaul. In the meanwhile, reports like this are very helpful.
