### ISSUE TITLE
Does ¬(p ↔ ¬p) need classical logic?

### ISSUE THREAD

**Issue by spl** [leanprover/tutorial#157]
In Section 3.6 (“Examples of Propositional Validities”), I found that I needed the excluded middle (`em`) for the following exercise:

```lean
example : ¬(p ↔ ¬p) := sorry
```

Is it possible to do this proof without `em`, or should this be moved under the following comment?

```lean
-- these require classical reasoning
```

**Comment by fpvandoorn** [comment]
Yes, this is constructively valid. Here is a constructive proof:
```lean
example (p : Prop) : ¬(p ↔ ¬p) :=
assume H : p ↔ ¬p,
have H2 : ¬ p, from
  assume p,
  show false, from iff.mp H p p,
show false, from H2 (iff.mpr H H2) 
```

**Comment by spl** [comment]
Awesome. I see that I got stuck on the recursiveness of the proof. Thanks!
