### ISSUE TITLE
Write Section 4.4 The Simplifier

### ISSUE THREAD

**Issue by spl** [leanprover/tutorial#160]
There is a TODO (989421d6c2c3b5c75878c6f4847eaebc87ba110e on Dec 8, 2014) for this:

> [TO DO: this section needs to be written. Emphasize that the simplifier can be used in conjunction with calc.]

But since there is no GitHub issue, I thought one should be added to track the matter.

**Comment by avigad** [comment]
Thanks for this. The sticking point is that we have been waiting for a simplifier! An earlier version of Lean had one, and a new one, being developed by Leo and Daniel, is starting to show signs of life. So hopefully we will be able to write this soon (and, more generally, add a chapter on automation).

**Comment by spl** [comment]
I look forward to reading about it.

**Comment by avigad** [comment]
The simplifier will be described in the new tutorial for Lean 3. (There are no longer plans to develop it for Lean 2.)
