### ISSUE TITLE
PDF tutorial page size

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#20]
On my PDF reader (Okular), "properties" says that the PDF tutorial is 6 by 9 inches. And when I print out a page, it is typeset in the upper right corner with about three inch margins on the left and bottom, and the topmost and rightmost part of the page are cut off.

**Comment by soonhokong** [comment]
You're right. We used the document class 'ebook' which uses 6 by 9 inches paper. It's for a small device such as Kindle. I changed it to use document class 'book' instead of 'ebook', which uses 8.5 by 11 inches paper (letter-size).

**Comment by soonhokong** [comment]
FYI, the new version is available at http://leanprover.github.io/tutorial/tutorial.pdf .
