### ISSUE TITLE
The characters ⦃ ⦄ are invisible in the tutorial PDF

### ISSUE THREAD

**Issue by leodemoura** [leanprover/tutorial#24]
BTW, they are fine in the HTML version.

Both characters are used in Section 10.2

**Comment by leodemoura** [comment]
Thanks! :+1:

**Comment by soonhokong** [comment]
![screen shot 2015-01-18 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/403281/5791482/5dc5b234-9f1b-11e4-95f9-33ca8f865ddd.png)

**Comment by soonhokong** [comment]
Dear @leodemoura, do you like it? I literally used '{' and '|' to define '{|':

```
\newunicodechar{⦃}{\ensuremath{\{\!|}}
\newunicodechar{⦄}{\ensuremath{|\!\}}}
```

Please pick better LaTeX symbols if you want :-)

**Comment by leodemoura** [comment]
It looks good. I didn't notice you were simulating it :-)

**Comment by soonhokong** [comment]
Great, that's good sign!!

FYI, our unicode <=> LaTeX symbol table [unixode.sty](https://github.com/leanprover/tutorial/blob/master/unixode.sty) is incomplete and we will have similar problem from time to time in the future. Please let me know if you notice something like this, I will add more entires on demand.

**Comment by leodemoura** [comment]
Great. I can try to fix it next time :-)

Thanks.
