### ISSUE TITLE
Failed example in chapter 2

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#25]
Dear @avigad, 

My friend @pondering sent me an email reporting an issue in the code example in chapter 2 (2.7 Implicit Arguments).

```lean
#+BEGIN_SRC lean
namespace hide
constant list : Type → Type

namespace list
  constant cons : ΠA : Type, A → list A → list A
  constant nil : ΠA : Type, list A
  constant append : ΠA : Type, list A → list A → list A
end list

-- BEGIN
open list

constant  A : Type
constant  a : A
constants l1 l2 : list A

check cons A a (nil A)
check append A (cons A a (nil A)) l1
check append A (append A (cons A a (nil A)) l1) l2
-- END
end hide
#+END_SRC
```

The last three checks generate errors. Could you take a look at and fix it?

@leodemoura, I remember that you mentioned a way to automatically check all the code in .org files. Could you elaborate it more? I'll integrate it in .travis.yml file so that we will get email notifications for any errors in the tutorial.

**Comment by leodemoura** [comment]
The script is called `test.sh`. The syntax is:
```
./test.sh <path-to-lean>  <org-file>
```
Here is an example:
```
 ./test.sh ../lean/bin/lean 02_Dependent_Type_Theory.org
```
Unfortunately, the script does not catch the problem you reported. The problem is that in the web version we automatically import `standard`. So, the behavior is different.
When we import `standard`, there are two namespaces `hide.list` and `list`, and `open list` is ambiguous. I modified `test.sh` to also import `standard`. I will also fix other similar problems.

**Comment by soonhokong** [comment]
By 7c63933 and 9cb47c1

**Comment by soonhokong** [comment]
@leodemoura, thanks!

@avigad, in 3e92bd8ebc842678847ee453ce18015a1bc2f67d, I added `test` target in the Makefile. You can run `make test` to test all the lean code in all org files. In case you need to specify lean binary, you can do it by running `LEAN_BIN=path/to/lean/binary make test`

We also run this in travis and send an email to lean-build@googlegroups.com if there is any error.

**Comment by soonhokong** [comment]
FYI, travis-ci is using the lean binary in the [ppa](https://launchpad.net/~leanprover/+archive/ubuntu/lean) which is slightliy outdated now. As a result, travis-ci generates generates the following error for `make test` command:

```
ERROR executing 10_Structures_Records.org.8.lean, for in_code_block block starting at 159, produced output:
10_Structures_Records.org.8.lean:2:0: warning: imported file uses 'sorry'
10_Structures_Records.org.8.lean:5:7: error: invalid binder, '(', '{', '[', '{{', '⦃' or identifier expected
10_Structures_Records.org.8.lean:6:7: error: invalid binder, '(', '{', '[', '{{', '⦃' or identifier expected
10_Structures_Records.org.8.lean:7:6: error: invalid expression
10_Structures_Records.org.8.lean:10:11: error: invalid binder, '(', '{', '[', '{{', '⦃' or identifier expected
```

I checked that the problem was already fixed by recent commits in lean repo. I'm sure that this problem is temporary and will be solved once we finish up automating PPA workflow.

FYI, the web page (leanprover.github.io/tutorial) is still updated even if there is an error in `make test`.

**Comment by avigad** [comment]
Thanks, Leo, for fixing the problem.

**Comment by leodemoura** [comment]
@soonhokong I can't update the ppa from home. I don't have the key on my home computer.
I will update the ppa first thing in the morning.
If you have your key with you, you can fix the problem by running the `update.sh` script.

**Comment by soonhokong** [comment]
@leodemoura, I ran `update.sh`. Now, we don't have the problem any more:

    https://travis-ci.org/leanprover/tutorial/jobs/47467828

**Comment by leodemoura** [comment]
Thanks!

**Comment by pondering** [comment]
Thanks.
