### ISSUE TITLE
change C-x to something else

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#29]
Prof. Klaus Sutner mentioned about this in the class. Actually current binding of executing code, `C-x`, is bad because it should do *cut*. I'm thinking about `shift-enter` or something with `enter`.

**Comment by leodemoura** [comment]
I like `shift-enter`

**Comment by soonhokong** [comment]
@leodemoura, thanks for the opinion. I'll change it, test in many browsers, and close this one.

**Comment by soonhokong** [comment]
also need to let users know about the shortcuts.

**Comment by soonhokong** [comment]
@leodemoura and @avigad, I've changed the keybinding to `shift+enter`. On my mac, it worked well in Chrome, Firefox, and Safari. But I couldn't tested it on Windows and Linux platforms. Could you try and let me know if you find a problem there? Thank you.

**Comment by avigad** [comment]
Nothing seems to have changed in the stand-alone version. The tutorial
version seems to work with shift-enter on Firefox. But in Chrome, if I
press "play" or "shift-enter" after Lean has loaded, with either an empty
input or 'print "hello"', the process freezes. The console window says
"Processing...". I can continue to edit the file, but pressing play again
or shift-enter does not produce any results.

**Comment by avigad** [comment]
I just confirmed that this also happens on my office computer (both my
laptop and office computer are running Kubuntu 13.10). Please let me know
if there is something else I can do to test.

**Comment by soonhokong** [comment]
I guess you're using Ubuntu, right? I will double check it.

**Comment by soonhokong** [comment]
Oops, you've mentioned that you're using Kubuntu.

**Comment by leodemoura** [comment]
I have the same problem with Ubuntu 14 + Chrome.

**Comment by avigad** [comment]
Sorry, I am also using 14.10. (The years are just flying by.)

On Sun, Jan 25, 2015 at 2:01 PM, Leonardo de Moura <notifications@github.com

**Comment by soonhokong** [comment]
Thanks for the reports. It's actually a bug coming from another fix. I'm working on it.

**Comment by soonhokong** [comment]
@avigad and @leodemoura, I think the problem is fixed. Could you check on your sides?

**Comment by avigad** [comment]
It works beautifully now. Thanks.

As far as the console window, right now "check", "eval", and "print" do not
show any output there, so there is not much reason for it. But it does
serve to confirm that a file compiled successfully.

@leodemoura, do you think we should show responses in the console window in
addition to the "i" and "x" annotations? Or leave it the way it is? Or get
rid of the console window entirely?

All of these options seem fine to me.

**Comment by soonhokong** [comment]
> Or get rid of the console window entirely?

In a previous email, @leodemoura mentioned about the reason for keeping the console window. For example, `lean.js` itself could fail and we need a place to display error messages.

I changed the default ratio between main editor and console window from 5 : 5 to 8 : 2. In addition to that, you can click the console icon to toggle it.

**Comment by soonhokong** [comment]
Let me close this one once I get a confirmation from @leodemoura.

**Comment by avigad** [comment]
I noticed the new ratio. With the "i" and "x" annotations, I guess there is
no reason to put responses in the console. So I think the behavior is ideal.

**Comment by leodemoura** [comment]
It looks great, but I notice a new behavior.
Now, some annotations (i or x) disappear if we modify the buffer.
Is this intended?

**Comment by soonhokong** [comment]
Yes. The intention is to remove the annotations which possibly are invalidated by changes. Please see it's https://github.com/leanprover/tutorial/issues/31

Q: Do you like it or is it mis-leading?

**Comment by avigad** [comment]
I think it is o.k. It is easy to press shift-enter to re-check.

**Comment by leodemoura** [comment]
@soonhokong It is still "ctrl-x" on the live website:
https://leanprover.github.io/live/

**Comment by soonhokong** [comment]
@leodemoura, I'm thinking about merging the live website and the tutorial website:

 - Add an icon to toggle the tutorial pane
 - Add an GET option to specify the initial value of it (something like `?tutorial=off`)

When it's done, "the live" link should point to https://leanprovier.github.io/tutorial/?tutorial=off (or something like that). Do you think it's a good plan?

**Comment by leodemoura** [comment]
I think merging is a good idea. 
I'm not sure if we need the icon. I think the GET option is enough.
What about `?tutorial=path`? The `path` indicates which html tutorial should be used with the web interface. If none is provided, then it is the "live" version.
I think this will be useful for the reference manual we will write in the future, and for any other form of documentation we may want to write.

**Comment by soonhokong** [comment]
> I think merging is a good idea. 

Great! For now, the live page is outdated and I really felt bad about it.

> I'm not sure if we need the icon.

In the live mode, I think it's better to hide the chapter navigation selector in the menu bar. With the tutorial icon, we can hide/show both of the tutorial pane and the selector. Let me first do it and show it to you, later we can change it.

> What about ?tutorial=path? The path indicates which html tutorial should be used with the web interface.

I like it. I'll do this.

> If none is provided, then it is the "live" version.

Just to clarify, this is what I have in mind:

 - https://leanprover.github.io/tutorial : show the first chapter of the tutorial
 - https://leanprover.github.io/tutorial?tutorial=none : live demo without showing the tutorial

Are we on the same page?

> I think this will be useful for the reference manual we will write in the future, and for any other form of documentation we may want to write.

Sure. Speaking of the reference manual, I think we need to figure out how to cite references/papers or other labels in the document in org-mode. There must be a way for this.

**Comment by leodemoura** [comment]
> Just to clarify, this is what I have in mind:
>
> https://leanprover.github.io/tutorial : show the first chapter of the tutorial
> https://leanprover.github.io/tutorial?tutorial=none : live demo without showing the tutorial
> 
> Are we on the same page?

I was not clear. Here is the refined version of the suggestion

- https://leanprover.github.io/live:   live demo
- https://leanprover.github.io/live?doc=tutorial:   show tutorial.html on the left hand side
- https://leanprover.github.io/live?doc=refmanual:   show refmanual.html on the left hand side

**Comment by soonhokong** [comment]
@leodemoura, thanks for the clarification. I created https://github.com/leanprover/tutorial/issues/35 for this.
