### ISSUE TITLE
weird scrolling

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#30]
sometimes the whole tutorial page is scrolled up slightly so that users can only see the bottom half of the top menu bar.

**Comment by soonhokong** [comment]
@avigad, could you let me know if you're still experiencing this with the new version (where there is no TOC)?

**Comment by avigad** [comment]
I can't reproduce the problem, but I will let you know if it comes back.

**Comment by soonhokong** [comment]
@avigad, let me close this one. Please feel free to re-open this one when you experience the problem again.
