### ISSUE TITLE
need a navigation for chapter/section

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#32]

**Comment by soonhokong** [comment]
@leodemoura and @avigad, I added the navigation, please check the new version at https://leanprover.github.io/tutorial

It still has some issues:

 - All chapters start with number 1, which should be fixed.
 - The navigation is hard-coded in `main_live.js` file, it should be dynamically generated by `Makefile`

I'll work on them.

**Comment by avigad** [comment]
Very nice!
