### ISSUE TITLE
merge live and tutorial

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#35]
https://github.com/leanprover/tutorial/issues/29#issuecomment-71517193
https://github.com/leanprover/tutorial/issues/29#issuecomment-71518498
https://github.com/leanprover/tutorial/issues/29#issuecomment-71519342

**Comment by soonhokong** [comment]
I'm in the classroom, watching a student who plays with [live](http://leanprover.github.io/live) page which is outdated. Let me do some quick fix:

 - add an argument to the tutorial page `?live=true` which disables tutorial pane (left) and the navigation bar (top). In that sense, it should be identical to the original live page.
 - redirect http://leanprover.github.io/live to http://leanprover.github.io/tutorial/?live=true

This is a temporary fix. I'll implement what @leodemoura mentioned in #29 later.

**Comment by soonhokong** [comment]
- Please test http://leanprover.github.io/tutorial/?live=1. It worked in Chrome/Safari/Firefox on my mac.
 - I've changed the link "TRY LEAN" to point to http://leanprover.github.io/tutorial/?live=1
 - http://leanprover.github.io/live is still outdated while there is no link to it now. Github pages do not support redirection with `.htaccess`. I'll think about alternatives.

**Comment by leodemoura** [comment]
> Please test http://leanprover.github.io/tutorial/?live=1. It worked in Chrome/Safari/Firefox on my mac.

It works on Win 8 (Chrome and IE)
It works on Linux (Chrome and Firefox)

**Comment by soonhokong** [comment]
> It works on Win 8 (Chrome and IE)
> It works on Linux (Chrome and Firefox)

Thank you!
