### ISSUE TITLE
get cross-chapter links working

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#44]
There is an example of a cross-chapter link in Section 8.1.

The following solution doesn't seem to work:

  http://stackoverflow.com/questions/4577709/emacs-org-mode-org-to-html-conversion-linking-to-section-in-a-different-page

**Comment by soonhokong** [comment]
@avigad, I've fixed this one. PDF and WWW versions are handled properly. Please note that I fixed the chapter 8: https://github.com/leanprover/tutorial/commit/1b0baf70617b007571a4706ea0e7abd4d8380b37
