### ISSUE TITLE
get _blank attribute working

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#45]
I tried this method with the first two links in Section 5.6, Notations, Overloads, and Coercions:

  http://orgmode.org/manual/Links-in-HTML-export.html#Links-in-HTML-export
  http://stackoverflow.com/questions/14217908/org-mode-export-to-html-links-open-in-new-tabs

It doesn't seem to work.

**Comment by soonhokong** [comment]
Closed by 26f3042 and f987cc2.

**Comment by soonhokong** [comment]
@avigad, you don't need to do anything special to let external link be opened in a new tab. Please see 26f3042 for details.
