### ISSUE TITLE
www version doesn't work in OSX+Safari env

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#46]
@awodey reported via @avigad.

I believe that this is due to 3453d606a730bf6930564c347eb1d332b1116ba0. I'll fix it soon.

**Comment by soonhokong** [comment]
It works in Chrome/Safari/Firefox on my mac. Please open an issue if you experience a problem in other platform+browser combinations.

**Comment by leodemoura** [comment]
@soonhokong, I just tried with my wife's mac air. It works perfectly.
She is using the latest version of the OS and Browser.
Perhaps, Steve is using an older version.

**Comment by soonhokong** [comment]
Dear Leo, good to know that it's working now. Actually I was able to
reproduce the problem on my macs. I pushed the commits to fix it.

BTW, could you check the IE when you are at MSR?

>

-- 
Soonho Kong
soonhok@cs.cmu.edu

**Comment by leodemoura** [comment]
It works perfectly on IE (Windows 8).
It doesn't work on Windows 7 + IE 9, but we knew that.

BTW, Tom Ball is reading the tutorial, and doing the exercises.
He is probably using IE.

**Comment by soonhokong** [comment]
> It works perfectly on IE (Windows 8).

Great!

> It doesn't work on Windows 7 + IE 9, but we knew that.

Yes.. https://github.com/kripken/emscripten/issues/495

> BTW, Tom Ball is reading the tutorial, and doing the exercises. He is probably using IE.

Good to know!

**Comment by awodey** [comment]
In fact, I updated to the latest version last night to check whether that was the problem, but it was not.
now however it is working fine, so the problem seems to have been fixed.
thanks,

Steve

**Comment by soonhokong** [comment]
@awodey, thank you for the confirmation. I will be more careful when I update the page.
