### ISSUE TITLE
test failure / chapter two / 2nd to the last code block

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#47]
@avigad, there is a test failure.

https://travis-ci.org/leanprover/tutorial/jobs/48726614

Code:
```lean
section
  variable {A : Type}
  variable x : A
  definition id := x
end

check id
check id a  // <-- fail
check id b  // <-- fail
```

Message:
```
ERROR executing 02_Dependent_Type_Theory.org.37.lean, for in_code_block block starting at 1049, produced output:
02_Dependent_Type_Theory.org.37.lean:2:0: warning: imported file uses 'sorry'
id : ?A → ?A
02_Dependent_Type_Theory.org.37.lean:9:9: error: unknown identifier 'a'
02_Dependent_Type_Theory.org.37.lean:10:9: error: unknown identifier 'b'
make: *** [test] Error 1
```

**Comment by avigad** [comment]
My apologies. I just issued a pull request to fix it, #48.

(Was there away to append the pull request to this issue?)

**Comment by soonhokong** [comment]
- Normally, I [close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages). 
 - In case you want to close an issue in repo `A` (i.e. leanprover/tutorial) by pushing a fix to repo `B` (i.e. avigad/tutorial), please read [closing issues across repositories](https://github.com/blog/1439-closing-issues-across-repositories).

**Comment by soonhokong** [comment]
Close by 2acdf485be92e7a79e803e136c695fb1513472b2

**Comment by avigad** [comment]
Thanks, this is helpful. But from the instructions it looks like I cannot
close an issue in leanprover/tutorial, because I do not have permission to
push to that repository. Have I misunderstood?

**Comment by soonhokong** [comment]
Dear @avigad, I haven't used the way to close an issue in other repositories, yet. However, I can think of two possible solutions:

 - When you commit, simply write "close #47" in the commit message. It will not close leanprover/tutorial#47 by the time you push the commit to `avigad/tutorial`. However, it will close leanprover/tutorial#47 by the time the pull-request is merged at `leanprover/tutorial`.

 - I can give you full permission on this repository. I actually wanted to ask you whether you want it or not. Please let me know what you like.

**Comment by soonhokong** [comment]
The first approach is what I'm using in `dreal/dreal` and `leanprover/lean`. From time to time, I think I fixed an issue but it turns out that it's not. It gives me some buffer to fix that kind of situation.
