### ISSUE TITLE
support citation

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#62]
Reference: 
 - HTML Export: https://github.com/yyr/org-mode/blob/master/contrib/lisp/ox-bibtex.el
 - PDF Export: http://tex.stackexchange.com/questions/114864/how-to-get-bibtex-to-work-with-org-mode-latex-export

**Comment by soonhokong** [comment]
Dear @avigad and @leodemoura

Please take a look at the example 63afcca3b1484b02c630090ab03d1fd4d82ae18c which shows how to add citations in the tutorial:

 1. Add bibtex items to `lean.bib`
 2. Use `\cite{key}` in `.org` as you do in `.tex`

Note: please install **`bibtex2html`** in your system. In Ubuntu, `sudo apt-get install bibtex2html` should do the job. In OS X, `brew install bibtex2html` works. Once you install it, `make` should compile everything (HTMLs and PDF).

Example (web)
---------------------
![screen shot 2015-02-12 at 11 48 40 pm](https://cloud.githubusercontent.com/assets/403281/6182437/c0b8979e-b311-11e4-9cee-a121948a8961.png)
![screen shot 2015-02-12 at 11 48 53 pm](https://cloud.githubusercontent.com/assets/403281/6182439/c52e69b6-b311-11e4-9fef-d92833e583c2.png)

Example (pdf)
---------------------
![screen shot 2015-02-12 at 11 48 17 pm](https://cloud.githubusercontent.com/assets/403281/6182442/d96a7fc8-b311-11e4-8ebc-350d6440d59c.png)
![screen shot 2015-02-12 at 11 48 26 pm](https://cloud.githubusercontent.com/assets/403281/6182444/de4dd17a-b311-11e4-96a3-fc28d35d5982.png)

**Comment by soonhokong** [comment]
Ooops.. I've added CoC citation ot CIC...

**Comment by avigad** [comment]
This looks great! I will modify this one and add more citations soon.

**Comment by soonhokong** [comment]
FYI, this is the bibtex file for Adam Chlipala's "Certified Programming with Dependent Types" book.

http://adam.chlipala.net/cpdt/repo/raw-file/aed0fcfabdbd/latex/cpdt.bib
