### ISSUE TITLE
Unsolvable Exercise in Chapter 4 

### ISSUE THREAD

**Issue by konn** [leanprover/tutorial#71]
In chapter 4, the following proposition is provided as exercise:

```lean
  example : (∃x : A, r) ↔ r := sorry
```

But, because there are no hypothesis assuming A is non-empty, I think this exercise cannot be shown.

**Comment by leodemoura** [comment]
Thanks for catching that.
I will split the exercise in two:
```lean
  example : (∃x : A, r) -> r := sorry
  example (H : inhabited A) : r -> (∃x : A, r) := sorry
```
