### ISSUE TITLE
explanation of nat -> (nat->nat) is wrong

### ISSUE THREAD

**Issue by goretkin** [leanprover/tutorial#75]
https://github.com/leanprover/tutorial/blob/03bfe1cb4733906a1ee15658213fd8295aecdf01/02_Dependent_Type_Theory.org#simple-type-theory

"the type of g is nat → (nat → nat). Thus we can view g as a function that takes natural numbers and returns a natural number."

should be something like "...and returns another function that takes a natural number and returns a natural number."

**Comment by leodemoura** [comment]
thanks for catching it
