### ISSUE TITLE
Issues with some symbolic shortcuts

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#81]
Created by @rkirsling in https://github.com/leanprover/leanprover.github.io/issues/30

---

Some of the backslash shortcuts aren't producing their expected output in the online editor.

According to the table in Chapter 3.3 of the tutorial:
* `\iff` and `\lr` should produce ↔
* `\not` and `\neg` should produce ¬

In the first case, `\lr` works as expected (as does `\<->` and `\leftrightarrow`), but `\iff` produces ⇔ instead, which results in an `unexpected token` error. The cause here seems to be [input-method.js#L689](https://github.com/leanprover/leanprover.github.io/blob/master/js/input-method.js#L689).

The second case is weirder: `\neg` works correctly (as does `\lnot`), but `\not` produces [U+0338](https://codepoints.net/U+0338), a sort of "combining slash" character. Looking at [input-method.js#L701](https://github.com/leanprover/leanprover.github.io/blob/master/js/input-method.js#L701) though, nothing really seems amiss. :confused:

**Comment by soonhokong** [comment]
Dear @avigad and @leodemoura,

> In the first case, \lr works as expected (as does \<-> and \leftrightarrow), but \iff produces ⇔ instead, which results in an unexpected token error.

I've noticed this one too. Do you see any problem in mapping `\iff` to ↔ instead of ⇔?

> The second case is weirder: \neg works correctly (as does \lnot), but \not produces U+0338, a sort of "combining slash" character

I think @avigad mentioned this one in lean-discuss list. If you don't mind, I'm happy to make the change.

FYI, [input-method.js](https://raw.githubusercontent.com/leanprover/tutorial/gh-pages/js/input-method.js) is automatically generated from [leanprover/lean/src/emacs/lean-input.el](https://github.com/leanprover/lean/blob/master/src/emacs/lean-input.el).

**Comment by rkirsling** [comment]
Looks like the root cause is simply that `\iff` and `\not` are being mapped to their MathJax defaults, since these sequences aren't specified in lean-input.el. (Same goes for `\leftrightarrow` and `\lnot`, though those are unproblematic.)

_I'm assuming this also means that `\iff` and `\not` are outright unrecognized in Emacs, but I've only tried the online editor so far._

**Comment by avigad** [comment]
Yes, both should be added to lean-input.el. @soonhokong, feel free to do this (or I will next time I add to the library).

**Comment by soonhokong** [comment]
@rkirsling and @avigad, I will fix it tonight.
