### ISSUE TITLE
Indication of constructive validity in list of propositional assertions

### ISSUE THREAD

**Issue by rkirsling** [leanprover/tutorial#84]
_Apologies in advance if this is needlessly nitpicky!_

Section 3.6 of the tutorial includes a "list of assertions in propositional logic" left for the reader to prove as an exercise, remarking that:

> Most of the assertions are constructively valid, but not all. For example, the last three require classical reasoning, as does `(p → r ∨ s) → ((p → r) ∨ (p → s))`, the forward direction of `¬ (p ∧ q) ↔ ¬ p ∨ ¬ q` and the reverse direction of `(¬ p ∨ q) ↔ (p → q)`.

Although qualified with "for example", this is **nearly** a complete listing of the places where classical reasoning is required (and leads the reader to believe it might be complete), except that:
- the forward direction of `¬(p → q) ↔ p ∧ ¬q` also requires it
- technically, only the backward direction of `(p → q) ↔ (¬q → ¬p)` (one of "the last three") requires it

That would result in an awfully long sentence though, so perhaps it would be cleaner to just mark the relevant assertions with comments in the code block. Simplest of all, one could just clump the classical assertions together at the end like this:

```lean
  -- these examples each require an instance of classical reasoning
  example : (p → r ∨ s) → ((p → r) ∨ (p → s)) := sorry
  example : ¬(p ∧ q) ↔ ¬p ∨ ¬q := sorry
  example : ¬(p → q) ↔ p ∧ ¬q := sorry
  example : (¬p ∨ q) ↔ (p → q) := sorry
  example : (p → q) ↔ (¬q → ¬p) := sorry
  example : p ∨ ¬p := sorry
  example : (((p → q) → p) → p) := sorry
```

Anyway, very low priority, but I thought I'd point it out. :smile:

**Comment by leodemoura** [comment]
Thanks! We are going to use your suggestion.
