### ISSUE TITLE
wrong titlebar in PDF reader

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#86]
When I open the tutorial in my PDF reader, the title bar shows the old title, "Dependent Types in Lean". I can't figure out where it is getting that from -- the title is correct in all the .org files. What is going on?

**Comment by soonhokong** [comment]
It comes from https://github.com/leanprover/tutorial/blob/244afa00a09b705d0d0dd7cb1e9a7cc91630c919/header/header.tex#L38

I'll fix it tonight. Thanks for the report!
