### ISSUE TITLE
Issues in existential quantification exercises

### ISSUE THREAD

**Issue by rkirsling** [leanprover/tutorial#87]
I noticed a few issues while going through the existential quantification exercises at the end of Chapter 4:

- `(∀x, p x → r) ↔ (∃x, p x) → r`

This one is actually unsolvable as written. Merely outlining the proof already results in an error:
```lean
example : (∀x, p x → r) ↔ (∃x, p x) → r :=
  iff.intro
    (assume H: (∀x, p x → r), sorry)
    (assume H: (∃x, p x) → r, sorry)
```  
Adding parentheses around the right side of the biconditional makes everything right again. I'm not sure whether this is a bug or just a typo.

- `(∃x, p x → r) ↔ (∀x, p x → r)`

This isn't valid. I think it's supposed to be `(∃x, p x → r) ↔ ((∀x, p x) → r)`?

- `(∃x, p x) ↔ (∀x, ¬p x)`  
  `(∀x, p x) ↔ (∃x, ¬p x)`

Neither of these are valid&mdash;each is missing an initial `¬` on the right side.

**Comment by fpvandoorn** [comment]
Thanks for reporting! I fixed all the issues in the pull requests above.
