### ISSUE TITLE
sections and local attributes

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/tutorial#89]
The tutorial uses a the `section` command a lot. Is this because previously all `variables` had to occur inside a `section`? Currently, you almost never need sections if you don't use `parameters`. Only if you want that your `variables` are unavailable later in the file, section is useful.

Do we want to change this?

Secondly: in chapter 5 and 8, it is wrongly states that the `local attribute` lasts till the end of the module. ~~They actually last until the end of the section (but only if no section is open, they last until the end of the module.~~

EDIT: `local attribute` and `local notation` also vanish when you close the enclosing namespace (and of course they vanish at the end of a context).

**Comment by fpvandoorn** [comment]
Okay, I'm confusing myself. I *think* that local attributes and notation last until the end of the namespace, and can persist past the end of a section (not past the end of a context, of course). Is that right?

**Comment by fpvandoorn** [comment]
For future reference: the behavior has been changed just after the previous comments. The current behavior is that local meta-information survives till the nearest enclosing namespace or section is closed (or till the end of the file if neither of the above apply).

The first issue still stands. I think we shouldn't mention the `section` command until chapter 8. Section has hardly any uses if you don't use parameters, and can be confusing (you cannot open namespaces in a section). The only use is if you want to stop using your declared variables, but you don't want to close the namespace. This is a very minor use, though (but should be mentioned in chapter 8).

I can change it, if this sounds good.

**Comment by leodemoura** [comment]
@fpvandoorn we also use `section`s for limiting the scope of an `open` command, the scope of a local attribute, local notation, etc.

I like your changes in chapter 5. You described precisely the scope of  the `local` command. If we only explain `section` in chapter 8, we will have to provide an approximate explanation for `local`, right?

**Comment by fpvandoorn** [comment]
Those are indeed also good uses for `section`. It's rare that you need to do one of those things, though.

Yes, if we explain section only in chapter 8, we probably shouldn't mention sections when describing the `local` command. That might be a problem for people who don't read the tutorial from a-z, but instead search it for specific information (which is probably almost everyone). We could still mention it, though: "local changes persist until the nearest enclosing namespace or section (see ...) is closed". Or we could give the approximate explanation, and in the section on `sections` give the amended explanation.

**Comment by leodemoura** [comment]
> Yes, if we explain section only in chapter 8, we probably shouldn't mention sections when describing the local command.

It sounds great!

**Comment by avigad** [comment]
One day we will have a reference manual which will make it easier to look up details, but for now, the tutorial has to serve that purpose. 

We can add cross-chapter links if that helps. There are some examples of that in Chapters 5 and 8. That makes it possible to add a sentence like "Later we will discuss Lean's section mechanism, and local definitions; see Section ..." or "Recall that in Section ... we discussed ....".

**Comment by avigad** [comment]
This doesn't seem urgent for Lean 2. The tutorial is being rewritten for Lean 3.
