### ISSUE TITLE
{} vs {{}} vs ⦃⦄

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/tutorial#92]
We should explain the difference between `{}` and `{{}}` and `⦃⦄`. I think section 2.8 (`Implicit Arguments`) is to early, but maybe we can add a new section in chapter 5 or 8 (`More on Implicit Arguments`?). There we can also briefly mention `[]` (with a forward reference to chapter 9) and explain `!foo`, which is currently unexplained, I believe (The only mention seems to be the sentence "Remember that the exclamation mark adds implicit arguments as necessary" in section 4.2).

I'll try to write something up along these lines, but I'd like some input whether to put this in chapter 5 or 8.

**Comment by leodemoura** [comment]
> I'll try to write something up along these lines, but I'd like some input whether to put this in chapter 5 or 8.

That would be great!

**Comment by avigad** [comment]
I agree. As to where to put it, I am not sure.

I try to imagine a reader working through the tutorial, starting with chapter 1, and learning to use the system. Too much technical information early on will overwhelm them, but we want them to have the information when it is useful.

In this case, either chapter 5 or 8 seems fine.
