### ISSUE TITLE
examples incorrectly sized in firefox

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/tutorial#93]
In Firefox some "Try it yourself" examples have a last line missing. Instead the examples are scrollable, and you can either see everything but the last line, or everything but the first line.

The screenshot below illustrates this. The top example on the left misses the last line (line 14 on the right). The bottom example misses the first line, since I scrolled down in that frame.

(In Chrome everything works fine)

![snapshot2](https://cloud.githubusercontent.com/assets/7376012/7307470/19d78290-e9db-11e4-93e0-d61efb939f14.png)

Firefox 37.0.1
Kubuntu 14.04

**Comment by leodemoura** [comment]
I managed to reproduce the problem. 
It depends on the window size and on the font size.
For example, for me, everything works fine when the firefox window is maximized.

**Comment by soonhokong** [comment]
@leodemoura and @fpvandoorn, I can reproduce the problem as well. I'm on it now.
